# -*- coding: utf-8 -*-
"""Génération du corps PDF de l'audit NEXUS PCB — route Report (ReportLab).

Règles appliquées : briefs/report.md (TOC Gate, numbering, tables, fonts),
typesetting/overflow.md (colWidths ≤ available), typesetting/pagination.md
(CondPageBreak H1, foliation), typesetting/charts.md (espacements figure).
"""
import hashlib
import os
import sys

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, Image, KeepTogether, PageBreak, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents
from PIL import Image as PILImage

import audit_content as C

# ── Fonts (registre autorisé uniquement) ────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback  # noqa: E402  (skill scripts)
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f5f5f6')
SECTION_BG    = colors.HexColor('#edeeef')
CARD_BG       = colors.HexColor('#e4e7e8')
TABLE_STRIPE  = colors.HexColor('#f2f4f4')
HEADER_FILL   = colors.HexColor('#405b69')
COVER_BLOCK   = colors.HexColor('#46565e')
BORDER        = colors.HexColor('#c7d3d9')
ICON          = colors.HexColor('#4f798f')
ACCENT        = colors.HexColor('#27698b')
ACCENT_2      = colors.HexColor('#bd5264')
TEXT_PRIMARY  = colors.HexColor('#212324')
TEXT_MUTED    = colors.HexColor('#747b7e')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_ODD = TABLE_STRIPE

# ── Géométrie de page ────────────────────────────────────────────────────
MARGIN = 1.0 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN            # ≈ 451 pt
AVAIL_H = PAGE_H - 2 * MARGIN
H1_COND = AVAIL_H * 0.25                 # pagination.md : seuil 25 %

# ── Styles ───────────────────────────────────────────────────────────────
S = {}
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                           alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceAfter=10)
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif-Bold', fontSize=20, leading=26,
                         textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif-Bold', fontSize=13.5, leading=19,
                         textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
S['toc_title'] = ParagraphStyle('TocTitle', fontName='FreeSerif-Bold', fontSize=20,
                                leading=26, textColor=TEXT_PRIMARY, spaceAfter=14)
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                              alignment=TA_CENTER, textColor=TEXT_MUTED)
S['th'] = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=13,
                         alignment=TA_LEFT, textColor=colors.white)
S['td'] = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9.5, leading=13,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY)
S['td_c'] = ParagraphStyle('TDC', parent=S['td'], alignment=TA_CENTER)
S['stat'] = ParagraphStyle('Stat', fontName='FreeSerif-Bold', fontSize=17, leading=21,
                           alignment=TA_CENTER, textColor=ACCENT)
S['stat_lbl'] = ParagraphStyle('StatLbl', fontName='FreeSerif', fontSize=7.8, leading=10,
                               alignment=TA_CENTER, textColor=TEXT_MUTED)
S['bullet'] = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                             alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                             leftIndent=14, spaceAfter=5)


def body(text):
    return Paragraph(text, S['body'])


def h1(num, text):
    """Titre de chapitre + filet accent, protégé contre l'orphelinage."""
    label = f'{num}.  {text}'
    key = 'h_' + hashlib.md5(f'{num}-{text}'.encode()).hexdigest()[:8]
    p = Paragraph(f'<a name="{key}"/><b>{label}</b>', S['h1'])
    p.bookmark_name = key
    p.bookmark_level = 0
    p.bookmark_text = f'{num}.  {text}'
    p.bookmark_key = key
    rule = HRFlowable(width='100%', thickness=1.6, color=ACCENT, spaceBefore=0, spaceAfter=14)
    return [CondPageBreak(H1_COND), KeepTogether([p, rule])]


def h2(text):
    return Paragraph(f'<b>{text}</b>', S['h2'])


def make_table(head, rows, ratios, center_cols=()):
    """Tableau centré, cellules Paragraph, largeur ≤ available (overflow.md)."""
    col_w = [r * AVAIL_W for r in ratios]
    assert sum(col_w) <= AVAIL_W + 0.5, 'table overflow'
    data = [[Paragraph(f'<b>{h}</b>', S['th']) for h in head]]
    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            st = S['td_c'] if i in center_cols else S['td']
            cells.append(Paragraph(str(cell), st))
        data.append(cells)
    t = Table(data, colWidths=col_w, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), colors.white if i % 2 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    return t


def callout_row(stats):
    """Rangée de 4 indicateurs — Data-to-Ink (report.md §CalloutBox)."""
    col_w = AVAIL_W / len(stats)
    stats_row = [Paragraph(f'<b>{v}</b>', S['stat']) for v, _ in stats]
    labels_row = [Paragraph(l, S['stat_lbl']) for _, l in stats]
    t = Table([stats_row, labels_row], colWidths=[col_w] * len(stats), hAlign='CENTER')
    style = [
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 2),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]
    for i in range(len(stats)):
        style.append(('BOX', (i, 0), (i, 1), 1, BORDER))
    t.setStyle(TableStyle(style))
    return t


def embed_image(path, max_width, max_height=260):
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(max_width / ow, max_height / oh, 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)


def figure(path, caption, max_height=250):
    img = embed_image(path, AVAIL_W * 0.94, max_height)
    return [Spacer(1, 18), KeepTogether([img, Spacer(1, 8), Paragraph(caption, S['caption'])]),
            Spacer(1, 18)]


# ── Gabarit de document (TOC Gate : TocDocTemplate + multiBuild) ─────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # folie relative au corps : la page brute 1 est le sommaire (i)
            self.notify('TOCEntry', (level, text, self.page - 1, key))


ROMAN = {1: 'i', 2: 'ii', 3: 'iii'}


def on_page(canvas, doc):
    canvas.saveState()
    # En-tête : titre + filet accent
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.62 * inch, 'Audit technique de complétude — NEXUS PCB')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.70 * inch, PAGE_W - MARGIN, PAGE_H - 0.70 * inch)
    # Pied : auteur + folio (sommaire en romain, corps en arabe redepart à 1)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, "Studio d'ingénierie NEXUS")
    folio = ROMAN.get(doc.page, '') if doc.page == 1 else str(doc.page - 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, folio)
    canvas.restoreState()


doc = TocDocTemplate(
    '/home/z/my-project/scripts/pdfbuild/audit_body.pdf',
    pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN,
    title=C.TITLE, author='Z.ai', creator='Z.ai', subject=C.SUBJECT,
)

story = []

# ── Sommaire (page i) ────────────────────────────────────────────────────
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11, leading=20,
                   leftIndent=6, textColor=TEXT_PRIMARY),
]
story.append(Paragraph('<b>Table des matières</b>', S['toc_title']))
story.append(HRFlowable(width='100%', thickness=1.6, color=ACCENT, spaceAfter=16))
story.append(toc)
story.append(PageBreak())

# ── Chapitre 1 — Synthèse exécutive ─────────────────────────────────────
head = h1(1, 'Synthèse exécutive')
story.extend(head[:2])
story.append(body(C.CH1_INTRO))
story.append(Spacer(1, 8))
story.append(callout_row(C.CH1_CALLS))
story.append(Spacer(1, 14))
story.append(body(C.CH1_BODY1))
story.append(body(C.CH1_BODY2))

# ── Chapitre 2 — Périmètre et méthode ───────────────────────────────────
story.extend(h1(2, "Périmètre et méthode d'audit"))
story.append(body(C.CH2_P1))
story.append(body(C.CH2_P2))
story.append(body(C.CH2_P3))

# ── Chapitre 3 — Architecture livrée ────────────────────────────────────
story.extend(h1(3, 'Architecture livrée'))
story.append(body(C.CH3_P1))
story.append(Spacer(1, 8))
story.append(make_table(C.CH3_TABLE_HEAD, C.CH3_TABLE, [0.22, 0.62, 0.16], center_cols=(2,)))
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 1 — Modules du moteur et de la plateforme audités', S['caption']))
story.append(Spacer(1, 14))
story.append(body(C.CH3_P2))

# ── Chapitre 4 — Grille de complétude fonctionnelle ─────────────────────
story.extend(h1(4, 'Grille de complétude fonctionnelle'))
story.append(body(C.CH4_P1))
story.append(Spacer(1, 8))
story.append(make_table(C.CH4_TABLE_HEAD, C.CH4_TABLE, [0.21, 0.38, 0.26, 0.15], center_cols=(3,)))
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 2 — Évaluation de complétude par domaine (pondérée par criticité)', S['caption']))
story.extend(figure('/home/z/my-project/scripts/pdfbuild/chart_domaines.png', C.CH4_CHART_CAPTION, max_height=265))
story.append(body(C.CH4_P2))

# ── Chapitre 5 — Résultats de validation ────────────────────────────────
story.extend(h1(5, 'Résultats de validation'))
story.append(body(C.CH5_P1))
story.extend(figure('/home/z/my-project/scripts/pdfbuild/chart_projets.png', C.CH5_CHART1_CAPTION, max_height=235))
story.append(body(C.CH5_P2))
story.append(Spacer(1, 8))
story.append(make_table(C.CH5_TABLE_HEAD, C.CH5_TABLE, [0.38, 0.62]))
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 3 — Campagne E2E navigateur, révision e21c796 (headless, souris et clavier réels)', S['caption']))
story.append(Spacer(1, 14))
story.append(body(C.CH5_P3))

# ── Chapitre 6 — Positionnement face aux références ─────────────────────
story.extend(h1(6, 'Positionnement face aux références'))
story.append(body(C.CH6_P1))
story.append(Spacer(1, 8))
story.append(make_table(C.CH6_TABLE_HEAD, C.CH6_TABLE, [0.16, 0.30, 0.54]))
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 4 — Briques différenciantes de la cible v2 et implémentations vérifiées', S['caption']))
story.append(Spacer(1, 14))
story.append(body(C.CH6_P2))

# ── Chapitre 7 — Dettes techniques et risques ───────────────────────────
story.extend(h1(7, 'Dettes techniques et risques'))
story.append(body(C.CH7_P1))
story.append(Spacer(1, 8))
story.append(make_table(C.CH7_RISK_HEAD, C.CH7_RISKS, [0.36, 0.34, 0.08, 0.22], center_cols=(2,)))
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 5 — Registre des risques et mitigations recommandées', S['caption']))
story.append(Spacer(1, 14))
story.append(body(C.CH7_P2))

# ── Chapitre 8 — Recommandations priorisées ─────────────────────────────
story.extend(h1(8, 'Recommandations priorisées'))
story.append(body(C.CH8_INTRO))
story.append(h2(C.CH8_P0_HEAD))
for i, item in enumerate(C.CH8_P0, 1):
    story.append(Paragraph(f'<b>P0.{i}</b>  {item}', S['bullet']))
story.append(h2(C.CH8_P1_HEAD))
for i, item in enumerate(C.CH8_P1, 1):
    story.append(Paragraph(f'<b>P1.{i}</b>  {item}', S['bullet']))
story.append(h2(C.CH8_P2_HEAD))
for i, item in enumerate(C.CH8_P2, 1):
    story.append(Paragraph(f'<b>P2.{i}</b>  {item}', S['bullet']))

# ── Chapitre 9 — Verdict de complétude ──────────────────────────────────
story.extend(h1(9, 'Verdict de complétude'))
story.append(body(C.CH9_P1))
story.append(Spacer(1, 8))
story.append(callout_row(C.CH9_CALLS))
story.append(Spacer(1, 14))
story.append(body(C.CH9_P2))

doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('Body OK :', doc.page, 'pages brutes')
